#!/bin/bash

touch /var/log/menu.log &>/dev/null
CURRENT_DIR=$(readlink /proc/$$/fd/255)
CURRENT_DIR=${CURRENT_DIR%/*}
TERM=linux
CONFIG=$CURRENT_DIR/config
MENULIB=$CURRENT_DIR/usr/share/menu_lib
DEF_COUNT=5
default="mainmenu"
baseopts="--stdout --output-fd 2 --colors --trim  --backtitle '${app[name]}' --cancel-label 'Назад' --ok-label 'Выбрать' --no-shadow --item-help"
tmpfile=/tmp/menu.$$
cmd=''
global_index=''
GLOBAL_PARAMS=$@
# hack to use anywhere
[ -f $CONFIG ] || CONFIG=config
[ -f $MENULIB ] || MENULIB=usr/share/menu_lib

declare -A main

. $CONFIG
# показывает главное menu на основе declare в конфиге
# widgetformat: 0 - type, 1 - label, 2 - describe

shopt -s extglob
. $MENULIB

create_mainmenu() {
	LOG ${FUNCNAME[0]} $@
	declare -A item
	local cmd="$cmd"
	local ITEM_COUNT=$DEF_COUNT
	while read tmp tmp array_name; do
		eval item=$(set | grep "^$array_name=" | sed s/$array_name=//)
		[ -z "${item['widget']}" ] && continue
		main[$array_name]=""
		main[$array_name.widget]="${item['widget']}"
		# echo "main[$array_name.widget]="${item['widget']}""
	done <<< "$(fgrep declare $CONFIG)"
	main[softreboot]=''
	main[softreboot.widget]="cmd 'Сохранить и применить настройки' 'save_and_exit && appctl ${app['appname']} restart'"
	main[widget]="menu 'Меню ${app['name']}'"
	return 0
}

create_mainmenu
show_recur main mainmenu
if dialog --yesno "Сохранить изменения?" 5 30; then
	save_and_exit
fi

